# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculadora.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(577, 568)
        self.slider_R = QtWidgets.QSlider(Form)
        self.slider_R.setGeometry(QtCore.QRect(20, 60, 160, 22))
        self.slider_R.setMinimum(1)
        self.slider_R.setMaximum(1000)
        self.slider_R.setProperty("value", 100)
        self.slider_R.setOrientation(QtCore.Qt.Horizontal)
        self.slider_R.setObjectName("slider_R")
        self.slider_C = QtWidgets.QSlider(Form)
        self.slider_C.setGeometry(QtCore.QRect(20, 140, 160, 22))
        self.slider_C.setMinimum(1)
        self.slider_C.setMaximum(100)
        self.slider_C.setProperty("value", 10)
        self.slider_C.setOrientation(QtCore.Qt.Horizontal)
        self.slider_C.setObjectName("slider_C")
        self.slider_V = QtWidgets.QSlider(Form)
        self.slider_V.setGeometry(QtCore.QRect(20, 220, 160, 22))
        self.slider_V.setMinimum(1)
        self.slider_V.setMaximum(20)
        self.slider_V.setProperty("value", 5)
        self.slider_V.setOrientation(QtCore.Qt.Horizontal)
        self.slider_V.setObjectName("slider_V")
        self.label_R = QtWidgets.QLabel(Form)
        self.label_R.setGeometry(QtCore.QRect(60, 30, 71, 16))
        self.label_R.setObjectName("label_R")
        self.label_C = QtWidgets.QLabel(Form)
        self.label_C.setGeometry(QtCore.QRect(60, 100, 81, 16))
        self.label_C.setObjectName("label_C")
        self.label_V = QtWidgets.QLabel(Form)
        self.label_V.setGeometry(QtCore.QRect(60, 180, 47, 13))
        self.label_V.setObjectName("label_V")
        self.widget_plot = QtWidgets.QWidget(Form)
        self.widget_plot.setGeometry(QtCore.QRect(10, 300, 561, 261))
        self.widget_plot.setObjectName("widget_plot")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(340, 20, 171, 41))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(360, 60, 121, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(370, 90, 101, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(400, 120, 47, 13))
        self.label_13.setObjectName("label_13")
        self.label_logo_1 = QtWidgets.QLabel(Form)
        self.label_logo_1.setGeometry(QtCore.QRect(310, 150, 231, 141))
        self.label_logo_1.setText("")
        self.label_logo_1.setPixmap(QtGui.QPixmap("../Punto #2.py/logo.png"))
        self.label_logo_1.setObjectName("label_logo_1")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_R.setText(_translate("Form", "RESISTENCIA"))
        self.label_C.setText(_translate("Form", "CAPACITANCIA"))
        self.label_V.setText(_translate("Form", "VOLTAJE"))
        self.label_10.setText(_translate("Form", "Prof. Fabian Barrera Prieto (MSc)."))
        self.label_11.setText(_translate("Form", "Ingeniería Mecatrónica"))
        self.label_12.setText(_translate("Form", "Electiva de robótica"))
        self.label_13.setText(_translate("Form", "2026 - 1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
