# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculadora.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(598, 583)
        self.layoutGrafica = QtWidgets.QWidget(Form)
        self.layoutGrafica.setGeometry(QtCore.QRect(280, 70, 261, 251))
        self.layoutGrafica.setObjectName("layoutGrafica")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(40, 100, 181, 61))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(90, 320, 111, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(100, 340, 101, 22))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(120, 360, 41, 31))
        self.label_13.setObjectName("label_13")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(60, 300, 163, 13))
        self.label_10.setObjectName("label_10")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 170, 221, 101))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboBox.setItemText(0, _translate("Form", "Cartesiano"))
        self.comboBox.setItemText(1, _translate("Form", "Cilíndrico"))
        self.comboBox.setItemText(2, _translate("Form", "Esférico"))
        self.label_11.setText(_translate("Form", "Ingeniería Mecatrónica"))
        self.label_12.setText(_translate("Form", "Electiva de robótica"))
        self.label_13.setText(_translate("Form", "2026 - 1"))
        self.label_10.setText(_translate("Form", "Prof. Fabian Barrera Prieto (MSc)."))
        self.label.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
