# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
from gpiozero import AngularServo

servo1 = AngularServo(17, min_angle=0, max_angle=180,
                      min_pulse_width=0.0005, max_pulse_width=0.0025)

servo2 = AngularServo(27, min_angle=0, max_angle=180,
                      min_pulse_width=0.0005, max_pulse_width=0.0025)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        self.centralwidget = QtWidgets.QWidget(MainWindow)

        # -------- TEXT EDIT --------
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(60, 220, 104, 71))

        # -------- SLIDER --------
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(40, 350, 160, 22))
        self.horizontalSlider.setMinimum(0)
        self.horizontalSlider.setMaximum(180)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)

        # -------- LABELS --------
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(230, 360, 241, 31))

        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(280, 440, 131, 16))

        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(290, 470, 121, 16))

        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(220, 500, 47, 13))

        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(40, 90, 250, 31))

        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(290, 20, 291, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_19.setFont(font)

        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(40, 120, 300, 31))

        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(40, 150, 300, 31))

        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(60, 400, 200, 31))

        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(250, 400, 250, 31))

        self.label_angulo = QtWidgets.QLabel(self.centralwidget)
        self.label_angulo.setGeometry(QtCore.QRect(90, 460, 100, 20))

        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(40, 323, 41, 20))

        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(120, 323, 41, 20))

        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(200, 323, 47, 20))

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(640, 420, 120, 22))

        MainWindow.setCentralWidget(self.centralwidget)

        # -------- TEXTOS --------
        self.retranslateUi(MainWindow)

        # -------- CONEXIÓN --------
        self.horizontalSlider.valueChanged.connect(self.mover_servo)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate

        MainWindow.setWindowTitle(_translate("MainWindow", "Mover Servomotor"))

        self.label_15.setText(_translate("MainWindow", "Prof. Fabian Barrera Prieto (MSc)."))
        self.label_16.setText(_translate("MainWindow", "Ingeniería Mecatrónica"))
        self.label_17.setText(_translate("MainWindow", "Electiva de robótica"))
        self.label_21.setText(_translate("MainWindow", "2026 - 1"))

        self.label_18.setText(_translate("MainWindow", "Seleccione Servomotor a mover:"))
        self.label_19.setText(_translate("MainWindow", "Mover Servomotor"))

        self.label_20.setText(_translate("MainWindow", "Escriba '1' para Servomotor 1"))
        self.label_22.setText(_translate("MainWindow", "Escriba '2' para Servomotor 2"))

        self.label_23.setText(_translate("MainWindow", "Ángulo del servomotor"))

        self.label_24.setText(_translate("MainWindow", "William Perez, David Sierra, Camilo Ruiz"))

        self.label_angulo.setText(_translate("MainWindow", "0°"))

        self.label_25.setText(_translate("MainWindow", "0°"))
        self.label_26.setText(_translate("MainWindow", "90°"))
        self.label_27.setText(_translate("MainWindow", "180°"))

        self.label.setText("")
        self.label.setGeometry(QtCore.QRect(530, 350, 256, 192))
        self.label.setPixmap(QtGui.QPixmap("/home/raspberrypi/Downloads/Taller2/imagen.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)


    # -------- FUNCIÓN PRINCIPAL --------
    def mover_servo(self):
        valor = self.horizontalSlider.value()

        # Mostrar ángulo
        self.label_angulo.setText(f"{valor}°")

        # Leer selección
        seleccion = self.textEdit_4.toPlainText().strip()

        if seleccion == "1":
            servo1.angle = valor
            self.label.setText("Servo 1")
        elif seleccion == "2":
            servo2.angle = valor
            self.label.setText("Servo 2")
        else:
            self.label.setText("Seleccione 1 o 2")
            print("⚠️ Escribe 1 o 2")


# -------- MAIN --------
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
