# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '3.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
import time
import random

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        self.centralwidget = QtWidgets.QWidget(MainWindow)

        # -------- LABELS --------
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(300, 430, 221, 21))

        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(350, 610, 47, 13))

        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(340, 486, 161, 20))

        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(300, 390, 231, 31))

        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(330, 455, 171, 21))

        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(300, 10, 291, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_19.setFont(font)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 122, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)

        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(80, 190, 104, 71))

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 210, 81, 21))

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 190, 151, 51))

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 360, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 440, 120, 21))

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(90, 470, 200, 30))

        # -------- IMAGEN --------
        self.label_imagen = QtWidgets.QLabel(self.centralwidget)
        self.label_imagen.setGeometry(QtCore.QRect(530, 350, 256, 192))
        self.label_imagen.setScaledContents(True)

        pixmap = QtGui.QPixmap("/home/raspberrypi/Downloads/Taller2/imagen.png")
        self.label_imagen.setPixmap(pixmap)

        MainWindow.setCentralWidget(self.centralwidget)

        # -------- TEXTOS --------
        self.retranslateUi(MainWindow)

        # -------- CONEXIÓN BOTÓN --------
        self.pushButton.clicked.connect(self.iniciar_lectura)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate

        MainWindow.setWindowTitle(_translate("MainWindow", "Sensor I2C"))

        self.label_24.setText(_translate("MainWindow", "William Perez, David, Camilo"))
        self.label_21.setText(_translate("MainWindow", "2026 - 1"))
        self.label_17.setText(_translate("MainWindow", "Electiva de robótica"))
        self.label_15.setText(_translate("MainWindow", "Prof. Fabian Barrera Prieto"))
        self.label_16.setText(_translate("MainWindow", "Ingeniería Mecatrónica"))

        self.label_19.setText(_translate("MainWindow", "LEER SENSOR I2C"))
        self.label.setText(_translate("MainWindow", "Tiempo (s):"))
        self.label_2.setText(_translate("MainWindow", "segundos"))

        self.pushButton.setText(_translate("MainWindow", "Iniciar"))

        self.label_3.setText(_translate("MainWindow", "Temperatura"))
        self.label_4.setText(_translate("MainWindow", "Valor:"))
        self.label_5.setText(_translate("MainWindow", "---"))

    # -------- FUNCIÓN PRINCIPAL --------
    def iniciar_lectura(self):
        try:
            tiempo = int(self.plainTextEdit.toPlainText())
        except:
            self.label_5.setText("Error en tiempo")
            return

        # 🔥 Intentar conexión REAL
        try:
            import board
            import busio
            import adafruit_bmp280

            i2c = busio.I2C(board.SCL, board.SDA)
            sensor = adafruit_bmp280.Adafruit_BMP280_I2C(i2c)

            modo = "REAL"

        except:
            modo = "SIMULADO"

        # -------- LECTURA --------
        for i in range(tiempo):

            if modo == "REAL":
                valor = sensor.temperature
            else:
                valor = random.uniform(20, 30)

            self.label_5.setText(f"{valor:.2f} °C ({modo})")

            QtWidgets.QApplication.processEvents()
            time.sleep(1)


# -------- MAIN --------
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
