# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '4.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
from gpiozero import Button

# -------- GPIO --------
boton = Button(17)  # GPIO 17


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        self.centralwidget = QtWidgets.QWidget(MainWindow)

        # -------- LABELS --------
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(260, 400, 250, 30))

        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(300, 500, 200, 20))

        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(290, 470, 200, 20))

        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(260, 430, 250, 30))

        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(290, 20, 291, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_20.setFont(font)

        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(100, 130, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)

        # 🔥 ESTE ES EL IMPORTANTE
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(110, 180, 150, 40))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setStyleSheet("background-color: blue; color: white;")

        # -------- IMAGEN --------
        self.label_imagen = QtWidgets.QLabel(self.centralwidget)
        self.label_imagen.setGeometry(QtCore.QRect(530, 370, 256, 192))
        self.label_imagen.setScaledContents(True)

        pixmap = QtGui.QPixmap("/home/raspberrypi/Downloads/Taller2/imagen.png")
        self.label_imagen.setPixmap(pixmap)

        MainWindow.setCentralWidget(self.centralwidget)

        # -------- TEXTOS --------
        self.retranslateUi(MainWindow)

        # 🔥 TIMER (LECTURA CONTINUA)
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.leer_estado)
        self.timer.start(100)  # cada 100 ms

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate

        MainWindow.setWindowTitle(_translate("MainWindow", "Lectura GPIO"))

        self.label_15.setText(_translate("MainWindow", "Prof. Fabian Barrera Prieto (MSc)."))
        self.label_17.setText(_translate("MainWindow", "Electiva de robótica"))
        self.label_16.setText(_translate("MainWindow", "Ingeniería Mecatrónica"))
        self.label_24.setText(_translate("MainWindow", "William Perez, David Sierra, Camilo Ruiz"))

        self.label_20.setText(_translate("MainWindow", "Lectura de estados"))
        self.label_6.setText(_translate("MainWindow", "Estado:"))

        self.label_7.setText(_translate("MainWindow", "BAJO"))

    # 🔥 FUNCIÓN DE LECTURA
    def leer_estado(self):
        if boton.is_pressed:
            self.label_7.setText("ALTO")
            self.label_7.setStyleSheet("background-color: red; color: white;")
        else:
            self.label_7.setText("BAJO")
            self.label_7.setStyleSheet("background-color: blue; color: white;")


# -------- MAIN --------
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
