# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '5.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
from gpiozero import OutputDevice
import time

# -------- GPIO --------
IN1 = OutputDevice(17)
IN2 = OutputDevice(18)
IN3 = OutputDevice(27)
IN4 = OutputDevice(22)

# Secuencia de pasos (full step)
SECUENCIA = [
    [1,0,0,0],
    [0,1,0,0],
    [0,0,1,0],
    [0,0,0,1]
]

PASOS_POR_VUELTA = 4096/8   # típico 28BYJ-48


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        self.centralwidget = QtWidgets.QWidget(MainWindow)

        # -------- LABELS --------
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(220, 400, 281, 31))

        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(320, 493, 71, 20))

        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(290, 466, 151, 20))

        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(240, 370, 241, 31))

        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(280, 436, 171, 20))

        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(210, 10, 451, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_20.setFont(font)

        # -------- INPUT --------
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(70, 210, 104, 71))

        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 160, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)

        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(30, 300, 321, 31))

        # -------- BOTÓN --------
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(210, 220, 181, 41))

        # -------- IMAGEN --------
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(550, 350, 200, 200))
        self.label.setScaledContents(True)

        pixmap = QtGui.QPixmap("/home/raspberrypi/Downloads/Taller2/imagen.png")
        self.label.setPixmap(pixmap)

        MainWindow.setCentralWidget(self.centralwidget)

        # -------- TEXTOS --------
        self.retranslateUi(MainWindow)

        # -------- CONEXIÓN --------
        self.pushButton.clicked.connect(self.mover_motor)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate

        MainWindow.setWindowTitle(_translate("MainWindow", "Motor Paso a Paso"))

        self.label_24.setText(_translate("MainWindow", "William Perez, David Sierra, Camilo Ruiz"))
        self.label_21.setText(_translate("MainWindow", "2026 - 1"))
        self.label_17.setText(_translate("MainWindow", "Electiva de robótica"))
        self.label_15.setText(_translate("MainWindow", "Prof. Fabian Barrera Prieto (MSc)."))
        self.label_16.setText(_translate("MainWindow", "Ingeniería Mecatrónica"))
        self.label_20.setText(_translate("MainWindow", "Manejo de Motores Paso a Paso"))

        self.label_8.setText(_translate("MainWindow", "Escriba el número de vueltas:"))
        self.label_22.setText(_translate("MainWindow", "Ej: 0.5, 1, 2.5"))

        self.pushButton.setText(_translate("MainWindow", "Accionar"))

    # -------- FUNCIÓN MOTOR --------
    def mover_motor(self):
        try:
            vueltas = float(self.textEdit_4.toPlainText())
            pasos = int(abs(vueltas) * PASOS_POR_VUELTA)

            for _ in range(pasos):
                for paso in SECUENCIA:
                    IN1.value = paso[0]
                    IN2.value = paso[1]
                    IN3.value = paso[2]
                    IN4.value = paso[3]
                    time.sleep(0.002)

        except:
            print("❌ Error en valor")


# -------- MAIN --------
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
