# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculadora.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wibget_grafica(object):
    def setupUi(self, wibget_grafica):
        wibget_grafica.setObjectName("wibget_grafica")
        wibget_grafica.resize(597, 584)
        self.lineEdit_min = QtWidgets.QLineEdit(wibget_grafica)
        self.lineEdit_min.setGeometry(QtCore.QRect(40, 170, 71, 20))
        self.lineEdit_min.setObjectName("lineEdit_min")
        self.lineEdit_max = QtWidgets.QLineEdit(wibget_grafica)
        self.lineEdit_max.setGeometry(QtCore.QRect(40, 210, 71, 20))
        self.lineEdit_max.setObjectName("lineEdit_max")
        self.combo_funcion = QtWidgets.QComboBox(wibget_grafica)
        self.combo_funcion.setGeometry(QtCore.QRect(30, 100, 91, 41))
        self.combo_funcion.setObjectName("combo_funcion")
        self.combo_funcion.addItem("")
        self.combo_funcion.addItem("")
        self.combo_funcion.addItem("")
        self.combo_funcion.addItem("")
        self.combo_funcion.addItem("")
        self.combo_funcion.addItem("")
        self.btn_graficar = QtWidgets.QPushButton(wibget_grafica)
        self.btn_graficar.setGeometry(QtCore.QRect(20, 260, 141, 61))
        self.btn_graficar.setObjectName("btn_graficar")
        self.widget_plot = QtWidgets.QWidget(wibget_grafica)
        self.widget_plot.setGeometry(QtCore.QRect(180, 10, 401, 401))
        self.widget_plot.setObjectName("widget_plot")
        self.label_6 = QtWidgets.QLabel(wibget_grafica)
        self.label_6.setGeometry(QtCore.QRect(30, 430, 171, 41))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(wibget_grafica)
        self.label_7.setGeometry(QtCore.QRect(50, 470, 121, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(wibget_grafica)
        self.label_8.setGeometry(QtCore.QRect(60, 500, 101, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(wibget_grafica)
        self.label_9.setGeometry(QtCore.QRect(80, 530, 47, 13))
        self.label_9.setObjectName("label_9")
        self.label_logo_1 = QtWidgets.QLabel(wibget_grafica)
        self.label_logo_1.setGeometry(QtCore.QRect(300, 430, 251, 141))
        self.label_logo_1.setText("")
        self.label_logo_1.setPixmap(QtGui.QPixmap("Punto A 2 corte.py/Punto #1.py/logo.png"))
        self.label_logo_1.setObjectName("label_logo_1")

        self.retranslateUi(wibget_grafica)
        QtCore.QMetaObject.connectSlotsByName(wibget_grafica)

    def retranslateUi(self, wibget_grafica):
        _translate = QtCore.QCoreApplication.translate
        wibget_grafica.setWindowTitle(_translate("wibget_grafica", "Form"))
        self.combo_funcion.setItemText(0, _translate("wibget_grafica", "sin"))
        self.combo_funcion.setItemText(1, _translate("wibget_grafica", "cos"))
        self.combo_funcion.setItemText(2, _translate("wibget_grafica", "tan"))
        self.combo_funcion.setItemText(3, _translate("wibget_grafica", "cot"))
        self.combo_funcion.setItemText(4, _translate("wibget_grafica", "sec"))
        self.combo_funcion.setItemText(5, _translate("wibget_grafica", "csc"))
        self.btn_graficar.setText(_translate("wibget_grafica", "GRAFICAR"))
        self.label_6.setText(_translate("wibget_grafica", "Prof. Fabian Barrera Prieto (MSc)."))
        self.label_7.setText(_translate("wibget_grafica", "Ingeniería Mecatrónica"))
        self.label_8.setText(_translate("wibget_grafica", "Electiva de robótica"))
        self.label_9.setText(_translate("wibget_grafica", "2026 - 1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wibget_grafica = QtWidgets.QWidget()
    ui = Ui_wibget_grafica()
    ui.setupUi(wibget_grafica)
    wibget_grafica.show()
    sys.exit(app.exec_())
